openapi: 3.0.0

info:
  title: "RMM model API practical"
  description: "A practical API to show the levels of the RMM model."
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Posts:
      type: "object"
      required:
        - title
      properties:
        title:
          type: "string"
        author:
          type: "string"
        content:
          type: "string"

    People:
      type: "object"
      properties:
        username:
          type: "string"
        name:
          type: "string"
        bio:
          type: "string"

    Places:
      type: "object"
      required:
        - name
      properties:
        name:
          type: "string"
        country:
          type: "string"
    
    Phones:
      type: "object"
      required:
        - name
      properties:
        name:
          type: "string"
        brand:
          type: "string"
        store:
          type: "string"
          
  parameters:
    title:
      name: "title"
      description: "Title of the posts"
      in: path
      required: True
      schema:
        type: "string"
      
    _id:
      name: "_id"
      description: "_id of the person"
      in: path
      required: True
      schema:
        type: "string"
    
    __id:
      name: "__id"
      description: "__id of the phone"
      in: path
      required: True
      schema:
        type: "string"

    name:
      name: "name"
      description: "Name of the places"
      in: path
      required: True
      schema:
        type: "string"

paths:
# Level zero - Swamp of POX
  /posts:
    get:
      operationId: "db.get_all_posts"
      tags:
        - Posts
      summary: "Get the list of posts"
      responses:
        "200":
          description: "Successfully read all posts"
    
    post:
      operationId: "db.add_post"
      tags:
        - Posts
      summary: "Add a post"
      requestBody:
        description: "Post to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "posts"
              $ref: "#/components/schemas/Posts"
      responses:
        "201":
          description: "Successfully created post"

# Level one - Resources, there will be no required field in the DB
  /people:
    post:
      operationId: "db.get_all_people"
      tags:
        - People
      summary: "Get list of people"
      responses:
        "200":
          description: "Successfully read all people"
  
  /people/{_id}:
    post:
      operationId: "db.get_one_person"
      tags:
        - People
      summary: "Get one person"
      parameters:
        - $ref: "#/components/parameters/_id"
      responses:
        "200":
          description: "Successfully read all people"

# Level two - Http Verbs
  /places:
      get:
        operationId: "db.get_all_places"
        tags:
          - Places
        summary: "Get the list of places"
        responses:
          "200":
            description: "Successfully read all places"

# Level three - HATEOAS
  /phones:
    get:
      operationId: "db.get_all_phones"
      tags:
        - Phones
      summary: "Get list of phone"
      responses:
        "200":
          description: "Successfully read all phones"
  
  /phones/{__id}:
    get:
      operationId: "db.get_one_phone"
      tags:
        - Phones
      summary: "Get one phone"
      parameters:
        - $ref: "#/components/parameters/__id"
      responses:
        "200":
          description: "Successfully read one phone"