openapi: 3.0.0

info:
  title: "RMM model API practical"
  description: "A practical API to show the levels of the RMM model."
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Posts:
      type: "object"
      required:
        - title
      properties:
        title:
          type: "string"
        author:
          type: "string"
        content:
          type: "string"

    People:
      type: "object"
      required:
        - username
      properties:
        username:
          type: "string"
        name:
          type: "string"
        bio:
          type: "string"

    Places:
      type: "object"
      required:
        - name
      properties:
        name:
          type: "string"
        country:
          type: "string"
          
  parameters:
    title:
      name: "title"
      description: "Title of the posts"
      in: path
      required: True
      schema:
        type: "string"
      
    username:
      name: "username"
      description: "Username of the users"
      in: path
      required: True
      schema:
        type: "string"

    name:
      name: "name"
      description: "Name of the places"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /posts:
    get:
      operationId: "db.get_all_posts"
      tags:
        - Posts
      summary: "Get the list of endpoints"
      responses:
        "200":
          description: "Successfully read all posts"
    
    post:
      operationId: "db.add_post"
      tags:
        - Posts
      summary: "Add a post"
      requestBody:
        description: "Post to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "posts"
              $ref: "#/components/schemas/Posts"
      responses:
        "201":
          description: "Successfully created post"